#!/bin/bash

#SBATCH -p 128x24   # Partition name
#SBATCH -J repeatlandscape        # Job name
#SBATCH --mail-user=aymays@ucsc.edu
#SBATCH --mail-type=ALL
#SBATCH -o repeatlandscape_aurelia.out    # Name of stdout output file
#SBATCH -N 1       # Total number of nodes requested (128x24/Instructional only)
#SBATCH -n 16        # Total number of mpi tasks requested per node
#SBATCH -t 64:00:00  # Run Time (hh:mm:ss) - 1.5 hours (optional)
#SBATCH --mem=12G # Memory to be allocated PER NODE

module load repeatmodeler

#input .divsum file (with divergence numbers) and genome size, then name the output html file
createRepeatLandscape.pl -div aurelia_aurita_genome.fna.tbl -g 376932402 > repeatlandscape_aurelia_aurita.html

#use filezilla to store html file to computer and open landscape graph on browser
